default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: skliarov_com_development

test:
  <<: *default
  database: skliarov_com_test

production:
  <<: *default
  database: skliarov_com_production
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
